// What's so special about finally?

try {
    console.log('HELLO')

} catch (error) {
    console.log(error)

} finally {
    console.log('I will always run')

}


// The significance of the finally block is that it'll always run regardless, 